name: amorim_smart_elearning
description: Aplicativo de e-learning construído em Flutter, inspirado no EduSmart E-learning UI Kit. Oferece navegação intuitiva por cursos, gestão de pagamento e temas claros/escuros para uma experiência de aprendizado otimizada.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: HK Grotesk
      fonts:
        - asset: fonts/HKGrotesk-Regular.ttf

  uses-material-design: true

  assets:
    - assets/profile.png
    - assets/books.svg